spring:
  application:
    name: demo-eureka-app-b


server:
    port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAdress: true

