spring:
  application:
    name: demo-eureka-app-c


server:
  port: 8083


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAdress: true
